version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.11
    - 8.2.12
    - 8.2.9
  - dependency-name: vite
    versions:
    - 2.1.4
    - 2.2.1
  - dependency-name: tailwindcss
    versions:
    - 2.1.0
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
